services:
  - type: web
    name: naivas-promo
    runtime: static
    repo: https://github.com/charlesnduya-png/naivas-promo
    branch: main
    buildCommand: "echo Static site ready"
    staticPublishPath: .
    autoDeployTrigger: commit
